{"name": "Проверка создания двух одинаковых курьеров. Возвращается ошибка", "status": "passed", "start": 1711638673669, "stop": 1711638673973, "uuid": "87ef0dfc-b4c3-4cbb-a3bd-4af0cc2346cc", "historyId": "b7fedf9cbe4876fe388ed6815949725e", "testCaseId": "b7fedf9cbe4876fe388ed6815949725e", "fullName": "test_courier.TestsCourier#test_create_courier_two_identical_show_error", "labels": [{"name": "suite", "value": "test_courier"}, {"name": "subSuite", "value": "TestsCourier"}, {"name": "host", "value": "DESKTOP-TQ0O0FL"}, {"name": "thread", "value": "10184-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_courier"}]}