{"name": "Проверка создания пользователя с логином, который уже есть. Возвращается ошибка", "status": "passed", "start": 1711638673058, "stop": 1711638673666, "uuid": "f318bc0c-45cd-4b52-9204-d1d8bfcdb460", "historyId": "a2350ecf85ab1aa74e14c1c54a1d3baa", "testCaseId": "a2350ecf85ab1aa74e14c1c54a1d3baa", "fullName": "test_courier.TestsCourier#test_create_courier_two_identical_login_show_error", "labels": [{"name": "suite", "value": "test_courier"}, {"name": "subSuite", "value": "TestsCourier"}, {"name": "host", "value": "DESKTOP-TQ0O0FL"}, {"name": "thread", "value": "10184-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_courier"}]}